use std::{path::PathBuf, sync::Arc};

use ls_types::{
    CompletionParams, CompletionResponse, Position, TextDocumentIdentifier,
    TextDocumentPositionParams, Uri,
};
use wasm_bindgen::prelude::*;
use zeek_language_server::{
    ast::Ast,
    complete::complete,
    lsp::{Database, SourceUpdate, hover_at},
};

// C stdlib shims so tree-sitter's libc calls resolve internally, not as WASM "env" imports.
mod wasm_libc;

// Embedded stdlib files generated by build.rs
include!(concat!(env!("OUT_DIR"), "/stdlib.rs"));

/// An LSP analysis session backed by an in-memory Zeek database.
#[wasm_bindgen]
pub struct Session {
    db: Database,
}

#[wasm_bindgen]
impl Session {
    /// Create a new session pre-loaded with the bundled Zeek stdlib.
    #[wasm_bindgen(constructor)]
    pub fn new() -> Session {
        let mut db = Database::default();

        // Set the stdlib prefix so @load resolution works.
        let prefix = PathBuf::from("/zeek/scripts");
        db.set_prefixes(Arc::from(vec![prefix]));

        // Seed the database with all bundled stdlib files.
        // Note: Uri::from_file_path() fails on wasm32-unknown-unknown, so we
        // construct file:// URIs directly from the virtual paths.
        let updates: Vec<SourceUpdate> = STDLIB_FILES
            .iter()
            .filter_map(|(path, content)| {
                let uri_str = format!("file://{path}");
                let uri = Arc::new(uri_str.parse::<Uri>().ok()?);
                Some(SourceUpdate::Update(uri, smol_str::SmolStr::from(*content)))
            })
            .collect();
        db.update_sources(&updates);

        Session { db }
    }

    /// Add or replace file content in the session.
    pub fn set_file(&mut self, uri: &str, content: &str) {
        if let Ok(uri) = uri.parse::<Uri>() {
            self.db.update_sources(&[SourceUpdate::Update(
                Arc::new(uri),
                smol_str::SmolStr::from(content),
            )]);
        }
    }

    /// Compute completions at a position. Returns JSON (LSP CompletionList) or null.
    pub fn complete(&self, uri: &str, line: u32, col: u32) -> JsValue {
        let result = (|| -> Option<CompletionResponse> {
            let uri: Uri = uri.parse().ok()?;
            let params = CompletionParams {
                text_document_position: TextDocumentPositionParams {
                    text_document: TextDocumentIdentifier { uri },
                    position: Position::new(line, col),
                },
                work_done_progress_params: Default::default(),
                partial_result_params: Default::default(),
                context: None,
            };
            complete(&self.db, params)
        })();

        match result {
            Some(r) => serde_wasm_bindgen::to_value(&r).unwrap_or(JsValue::NULL),
            None => JsValue::NULL,
        }
    }

    /// Compute hover information at a position. Returns JSON (LSP Hover) or null.
    pub fn hover(&self, uri: &str, line: u32, col: u32) -> JsValue {
        let result = (|| -> Option<_> {
            let uri: Uri = uri.parse().ok()?;
            hover_at(&self.db, Arc::new(uri), Position::new(line, col))
        })();

        match result {
            Some(h) => serde_wasm_bindgen::to_value(&h).unwrap_or(JsValue::NULL),
            None => JsValue::NULL,
        }
    }
}
